package consts

const (
	NHDL_PORT_KEY     = "NHDL_PORT"
	NHDL_PORT_DEFAULT = "3001"

	NHDL_CACHE_PATH_KEY     = "NHDL_CACHE_PATH"
	NHDL_CACHE_PATH_DEFAULT = "./cache"

	NHDL_DOWNLOAD_PATH_KEY     = "NHDL_DOWNLOAD_PATH"
	NHDL_DOWNLOAD_PATH_DEFAULT = "./download"

	NHDL_LOGS_PATH_KEY     = "NHDL_LOGS_PATH"
	NHDL_LOGS_PATH_DEFAULT = "./logs"

	NHDL_PROXY_KEY     = "NHDL_PROXY"
	NHDL_PROXY_DEFAULT = ""

	NHDL_RETRIED_KEY     = "NHDL_DOWNLOAD_PATH"
	NHDL_RETRIED_DEFAULT = "10"

	NHDL_LANRARAGI_URL_KEY     = "NHDL_LANRARAGI_URL"
	NHDL_LANRARAGI_URL_DEFAULT = "http://127.0.0.1:3000/"

	NHDL_LANRARAGI_KEY_KEY = "NHDL_LANRARAGI_KEY"
)
